<a href="https://colab.research.google.com/github/VladimirPakhomov2000/Base-syntaxis-Python/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%91%D0%B8%D0%B1%D0%BB%D0%B8%D0%BE%D1%82%D0%B5%D0%BA%D0%B0_Numpy_(%D0%A3%D0%BD%D0%B8%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%82%D0%B5%D1%82_%D0%B8%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%B8%D0%BD%D1%82%D0%B5%D0%BB%D0%BB%D0%B5%D0%BA%D1%82%D0%B0)%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Библиотека NumPy

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=1

NumPy - векторные/научные вычисления. Пакет содержит функциональные средства для работы с многомерными массивами и высокоуровневыми математическими функциями.

Справочные материалы по numpy: https://pythonworld.ru/numpy

Импортирование библиотеки:

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=38

In [ ]:
import numpy as np # Подключаем библиотеку numpy и задаем ей псевдоним np

### 1. Структура np.ndarray

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=480



np.ndarray - это массив, содержащий элементы **одного типа**. 

Давайте посмотрим, что это значит:

In [ ]:
my_list1 = [2, 4, 5] # Создаем переменную my_list1 и записываем в нее список из трех значений
print (my_list1) # Выводим на экран созданный список
print (type(my_list1)) # Выводим на экран тип переменной my_list1

[2, 4, 5]
<class 'list'>


In [ ]:
my_numpy1 = np.array(my_list1) # Создаем numpy-массив из списка my_list1
print(my_numpy1) # Выводим на экран созданный numpy-массив
print(type(my_numpy1)) # Выводим на экран тип переменной my_numpy1
print(my_numpy1.dtype) # Выводим на экран тип элементов массива my_numpy1

[2 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
my_list2 = [2, 3.14] # Создаем переменную my_list_float и записываем в нее список из двух значений (типа int и типа float)
my_numpy2 = np.array(my_list2) #  Создаем numpy-массив из списка my_list2
print(my_numpy2.dtype)  # Выводим на экран тип элементов массива my_numpy2

float64


In [ ]:
print(my_list2) # Выводим на экран созданный список my_list2
print(my_numpy2) # Выводим на экран созданный массив my_numpy2

[2, 3.14]
[2.   3.14]


In [ ]:
my_list3 = [2, 3.14, 'text data'] # Создаем переменную my_list2 и записываем в нее список из трех значений (типа int, типа float и типа str)
my_numpy3 = np.array(my_list3) # Создаем numpy-массив из списка my_list3
print(my_list3) # Выводим на экран созданный список my_list3
print(my_numpy3) # Выводим на экран созданный массив my_numpy3
print(my_numpy3.dtype) # Выводим на экран тип элементов массва my_numpy3

[2, 3.14, 'text data']
['2' '3.14' 'text data']
<U32


In [ ]:
my_list4 = [2, 3.14, 'text data', [2,3,4]] # Создаем переменную my_list4 и записываем в нее список из четырех значений (типа int, типа float, типа str  и список)
print(my_list4) # Выводим на экран созданный список my_list4

[2, 3.14, 'text data', [2, 3, 4]]


In [ ]:
my_numpy4 = np.array(my_list4) # Создаем numpy-массив из списка my_list3
print(my_numpy4) # Выводим на экран созданный массив my_numpy4
print(my_numpy4.dtype) # Выводим на экран тип элементов массива my_numpy4

[2 3.14 'text data' list([2, 3, 4])]
object


In [ ]:
my_numpy5 = np.array([2, 3.14, 'text data', [2, 4, 5]], dtype='object') # Создаем numpy-массив из списка и указываем тип элементов - 'object'
print(my_numpy5) # Выводим на экран созданный массив my_numpy5
print(my_numpy5.dtype) # Выводим на экран тип элементов массива my_numpy5

[2 3.14 'text data' list([2, 4, 5])]
object


In [ ]:
my_numpy6 = np.array([2, 3.14, 'text data', [2, 4, 5]], dtype='int64') # Создаем numpy-массив из списка и указываем тип элементов - 'int'

ValueError: ignored

In [ ]:
my_numpy7 = np.array([2, 3.14], dtype='int64') # Создаем numpy-массив из списка и указываем тип элементов - 'int'
print(my_numpy7) # Выводим на экран созданный массив my_numpy5
print(my_numpy7.dtype) # Выводим на экран тип элементов массива my_numpy5

[2 3]
int64


### 2. Типы данных

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=1306

В NumPy реализованы свои типы данных, которые отличаются от встроенных в Python.

Подробнее о типах: https://docs.scipy.org/doc/numpy/user/basics.types.html

Например, встроенный тип int ничем не ограничен (кроме вашей памяти). Целые числа в numpy имеют фиксированный размер: np.int8, np.int16...

Другое различие кроется во встроенных методах:

In [ ]:
value = -167 # Создаем переменную value и записываем в нее значение
numpy_value = np.uint8(value) # Преобразуем переменную value к типу np.uint8

In [ ]:
print(value) # Выводим на экран значение переменной value

-167


In [ ]:
print(numpy_value) # Выводим на экран значение переменной numpy_value

89


In [ ]:
print(type(value)) # Выводим на экран тип переменной value

<class 'int'>


In [ ]:
print(type(numpy_value)) # Выводим на экран тип переменной numpy_value

<class 'numpy.uint8'>


### 3. Одномерные массивы

#### Одномерные numpy массивы

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=1691


In [ ]:
numpy_digital = np.array([1, 2, 3, 4, 5]) # Создаем numpy-массив из списка цифр

In [ ]:
numpy_str = np.array(['cat', 'mouse', 'dog', 'rat']) # Создаем numpy-массив из списка слов 

In [ ]:
print(numpy_digital.dtype) # Выводим на экран тип элементов массива numpy_digital

int64


In [ ]:
print(numpy_str.dtype) # Выводим на экран тип элементов массива numpy_str

<U5


In [ ]:
print(numpy_digital.shape) # Выводим на экран размерность массива numpy_digital

(5,)


In [ ]:
print(numpy_str.shape) # Выводим на экран размерность массива numpy_str

(4,)


In [ ]:
print(numpy_digital.size) # Выводим на экран количество элементов массива numpy_digital

5


In [ ]:
numpy_digital2 = np.array([1, 2, 3, 4, 5, 6]) # Создаем numpy-массив из списка цифр
print(numpy_digital2) # Выводим на экран массив numpy_digital
print(numpy_digital2.shape) # Выводим на экран размерность массива numpy_digital

[1 2 3 4 5 6]
(6,)


In [ ]:
numpy_new = numpy_digital2.reshape((3, 2)) # Изменяем размерность массива numpy_digital2 из (6,) -> (3, 2)
print(numpy_new) # Выводим на экран массив numpy_new
print(numpy_new.shape) # Выводим на экран размерность массива numpy_new
print(numpy_new.size) # Выводим на экран количество элементов массива numpy_new

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [ ]:
numpy_new2 = numpy_digital2.reshape((2, 3)) # Изменяем размерность массива numpy_digital2 из (6,) -> (2, 3)
print(numpy_new2) # Выводим на экран массив numpy_new2
print(numpy_new2.shape) # Выводим на экран размерность массива numpy_new2
print(numpy_new2.size) # Выводим на экран количество элементов массива numpy_new2

[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [ ]:
numpy_new3 = numpy_digital2.reshape((1, 6)) # Изменяем размерность массива numpy_digital2 из (6,) -> (1, 6)
print(numpy_new3) # Выводим на экран массив numpy_new3
print(numpy_new3.shape) # Выводим на экран размерность массива numpy_new3
print(numpy_new3.size) # Выводим на экран количество элементов массива numpy_new3

[[1 2 3 4 5 6]]
(1, 6)
6


In [ ]:
print(numpy_digital2) # Выводим на экран массив numpy_new
print(numpy_digital2.shape) # Выводим на экран размерность массива numpy_new
print(numpy_digital2.size) # Выводим на экран количество элементов массива numpy_new

[1 2 3 4 5 6]
(6,)
6


In [ ]:
print(numpy_digital) # Выводим на экран массив numpy_new
print(numpy_digital.shape) # Выводим на экран размерность массива numpy_digital

[1 2 3 4 5]
(5,)


In [ ]:
numpy_new4 = numpy_digital.reshape((2, 3)) # Изменяем размерность массива numpy_digital из (5,) -> (2, 3)

ValueError: ignored

#### Индексация

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=2363


In [ ]:
numpy_new5 = np.array([102,123,33,54,25,136]) # Создаем numpy-массив из списка цифр
print(numpy_new5) # Выводим на экран массив numpy_new5

[102 123  33  54  25 136]


In [ ]:
print(numpy_new5[0]) # Выводим на экран нулевой элемент массива numpy_new5

102


In [ ]:
print(numpy_new5[1]) # Выводим на экран первый элемент массива numpy_new5

123


In [ ]:
print(numpy_new5[-1]) # Выводим на экран последний (минус первый) элемент массива numpy_new5

136


In [ ]:
print(numpy_new5[:]) # Выводим на экран все элементы массива numpy_new5

[102 123  33  54  25 136]


In [ ]:
print(numpy_new5[1:]) # Выводим на экран все элементы массива numpy_new5, начиная с первого

[123  33  54  25 136]


In [ ]:
print(numpy_new5[:3]) # Выводим на экран с нулевого по третий элементы массива numpy_new5

[102 123  33]


In [ ]:
print(numpy_new5[-2:]) # Выводим на экран все элементы массива numpy_new5, начиная с предпоследнего

[ 25 136]


In [ ]:
print(numpy_new5[1:4]) # Выводим на экран с первого по четвертый элемент массива numpy_new5

[123  33  54]


In [ ]:
print(numpy_new5 > 55) # Выводим маску массива numpy_new5 для условия: значение элемента больше 55

[ True  True False False False  True]


In [ ]:
print(numpy_new5[(numpy_new5 > 25) & (numpy_new5 < 67)]) # Производим подвыборку элементов массива, значения которых больше 25 и меньше 67

[33 54]


In [ ]:
arr1 = np.array([2, 3, 12]) # Создаем numpy-массива из списка
arr2 = np.array([i for i in range(7)]) # Создаем numpy-массив с помощью генератора цикла

print(arr1) # Выводим массив arr1
print(arr2) # Выводим массив arr2

[ 2  3 12]
[0 1 2 3 4 5 6]


In [ ]:
mask = np.array([(i in arr2) for i in arr1]) # Создаем маску для массива arr1 по наличию элемента в массиве arr2

print(mask) # Выводим маску 

[ True  True False]


In [ ]:
arr1[mask]

array([2, 3])

#### Встроенные методы

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=3129


чтобы увидеть все доступные методы, после точки нажмите "Tab"

In [ ]:
numpy_array = np.array([1,2,3,4,5,6,7,8,9,10]) # Создаем numpy-массив из целых чисел
print(numpy_array) # Выводим на экран массив numpu_array

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(numpy_array.sum()) # Выводим на экран сумму всех элементов массива numpy_array

55


In [ ]:
print(numpy_array.mean()) # Выводим на экран среднее значение всех элементов массива numpy_array

5.5


In [ ]:
print(numpy_array.max()) # Выводим на экран максимальный элемент массива numpy_array

10


In [ ]:
print(numpy_array.min()) # Выводим на экран минимальный элемент массива numpy_array

1


In [ ]:
print(numpy_array.prod()) # Выводим на экран произведение всех элементов массива numpy_array

3628800


In [ ]:
str_array = np.array(['Один', 'Два','Три','Четыре']) # Создаем numpy-массив из четырех строковых значений
print(str_array) # Выводим на экран массив str_array

['Один' 'Два' 'Три' 'Четыре']


In [ ]:
str_array.sort() # Сортируем массив str_array
print(str_array) # Выводим на экран массив str_array

['Два' 'Один' 'Три' 'Четыре']


In [ ]:
my_type = [('city', '<U32'), ('region', np.int32)] # Создадим список, где укажем тип данных будущего массива
values = [('Москва', 99), ('Пенза', 58), ('Рязань', 62)] # Создадим список со значениями будущего массива
regions = np.array(values, dtype=my_type) # Создаем numpy-массива из указанных значений и задаем тип данных для каждого столбца
print(regions) # Выводим на экрам массив regions

[('Москва', 99) ('Пенза', 58) ('Рязань', 62)]


In [ ]:
regions['city'] # Обращаемся к столбцу массива по заданному имени

array(['Москва', 'Пенза', 'Рязань'], dtype='<U32')

In [ ]:
%%timeit
numpy_array.sum() # Считаем сумму элементов массива numpy_array и смотрим на время выполнения операции с помощью магической команды timeit

The slowest run took 31.62 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.11 µs per loop


In [ ]:
%%timeit
numpy_array.mean() # Считаем среднее значение элементов массива numpy_array и смотрим на время выполнения операции с помощью магической команды timeit

The slowest run took 24.64 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 5.58 µs per loop


In [ ]:
%%timeit
numpy_array.sum()
numpy_array.mean()

The slowest run took 19.51 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.94 µs per loop


In [ ]:
# Задаем параметры 
## n - кол-во циклов повторений
## r - кол-во повторений в одном цикле

In [ ]:
%%timeit -n 5 -r 10
numpy_array.sum()

The slowest run took 4.06 times longer than the fastest. This could mean that an intermediate result is being cached.
5 loops, best of 10: 3.57 µs per loop


#### Операции с массивами

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=3653


In [ ]:
numpy_10 = np.arange(5) # Создаем numpy-массив из последовательности элементов от 0 до 4 (5 не включается)
print(numpy_10) # Выводим на экран массив numpy_10

[0 1 2 3 4]


In [ ]:
numpy_11 = np.arange(3, 6) # Создаем numpy-массив из последовательности элементов от 3 до 5 (6 не включается)
print(numpy_11) # Выводим на экран массив numpy_11

[3 4 5]


In [ ]:
numpy_12 = np.arange(3, 16, 4) # Создаем numpy-массив из последовательности элементов от 3 до 15 с шагом 4
print(numpy_12) # Выводим на экран массив numpy_12

[ 3  7 11 15]


#### Векторные операции

*Разбор данного раздела:* https://youtu.be/g1Wa_1iKRPY?t=3719


In [ ]:
my_list1 = [0,1,2,3,4,5] # Создаем список из 5 элементов
my_list2 = [6,7,8,9,10,11] # Создаем еще один список также из 5 элементов
my_numpy1 = np.array(my_list1) # Создаем массив из списка my_list1
my_numpy2 = np.array(my_list2) # Создаем массив из списка my_list2
print(my_list1 + my_list2) # Выводим результат сложения двух списков
print(my_numpy1 + my_numpy2) # Выводим результат сложения двух массивов

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
[ 6  8 10 12 14 16]


In [ ]:
print(my_numpy1 - my_numpy2) # Выводим разность двух массивов

[-6 -6 -6 -6 -6 -6]


In [ ]:
print(my_list1 - my_list2) # Выводим рвзность двух списков

TypeError: ignored

In [ ]:
print(my_numpy1 / my_numpy2) # Выводим частное двух массивов

[0.         0.14285714 0.25       0.33333333 0.4        0.45454545]


In [ ]:
# обратите внимание, что python нормально обработал деление на ноль
## inf - infinite value, бесконочность
print(my_numpy2 / my_numpy1) # Выводим частное двух массивов

[inf 7.  4.  3.  2.5 2.2]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
print(my_numpy1 * my_numpy2) # поэлементное умножение двух массивов

[ 0  7 16 27 40 55]


In [ ]:
print(my_numpy1 ** my_numpy2) # поэлементное возведение в степень

[       0        1      256    19683  1048576 48828125]


In [ ]:
# методы работают и без создания новой переменной, но нужны скобочки ()
print(((my_numpy1 * my_numpy2 - my_numpy1) ** 2).sum()) # Выведем сумму элементов "составного" массива

4604


In [ ]:
print(my_numpy1 * 5 + my_numpy2[0] * 17)

[102 107 112 117 122 127]


### 4. Многомерные массивы

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=5

2D - матрица

3D, ..., nD - тензоры

In [ ]:
# создаем двумерный массив
my_2d_array = np.array([[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]])

print(my_2d_array)

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
# создаем трехмерный массив
my_3d_array = np.array([[[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]]])

print(my_3d_array)

[[[3 6 2 7]
  [9 2 4 8]
  [8 2 3 6]]]


In [ ]:
print(my_2d_array.shape) # Выводим на экран размерность массива my_2d_array
print(my_3d_array.shape) # Выводим на экран размерность массива my_3d_array

(3, 4)
(1, 3, 4)


In [ ]:
# кол-во элементов массива
print(my_2d_array.size) # Выводим на экран количество элементов массива my_2d_array
print(my_3d_array.size) # Выводим на экран количество элементов массива my_3d_array

12
12


#### Индексация

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=458

построчно

In [ ]:
# Создадим двумерный массив
my_2d_array2 = np.array([[3, 6, 2, 7],
                        [9, 2, 4, 8],
                        [8, 2, 3, 6]])

print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
print(my_2d_array2[0]) # Выведем на экран нулевую строку

[3 6 2 7]


In [ ]:
# первая строка
print(my_2d_array2[1]) # Выведем на экран первую строку
print(my_2d_array2[-1]) # Выведем на экран последнюю строку

[9 2 4 8]
[8 2 3 6]


поэлементно

In [ ]:
print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
print(my_2d_array2[0,0]) # Выведем на экран элемент с индексом [0,0] (нулевая строка, нулевой столбец)

3


In [ ]:
print(my_2d_array2[0,1]) # Выведем на экран элемент с индексом [0,1] (нулевая строка, первый столбец)

6


In [ ]:
print(my_2d_array2[1,2]) # Выведем на экран элемент с индексом [1,2] (первая строка, второй столбец)

4


по столбцам

In [ ]:
print(my_2d_array2[:, 0]) # Выведем на экран нулевой столбец

[3 9 8]


In [ ]:
print(my_2d_array2[:, 1]) # Выведем на экран первый столбец

[6 2 2]


In [ ]:
print(my_2d_array2[1:, 1]) # Выведем на экран первый столбец  и все элементы этого столбца, начиная с первого

[2 2]


#### Операции с двумерными массивами и встроенные методы

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=704


In [ ]:
print(my_2d_array2) # Выведем на экран массив my_2d_array2

[[3 6 2 7]
 [9 2 4 8]
 [8 2 3 6]]


In [ ]:
print(my_2d_array2.sum()) # Выводим сумму элементов двумерного массива

60


In [ ]:
print(my_2d_array2.min(axis=1)) # Выводим минимальный элемент в каждой строке

[2 2 2]


In [ ]:
print(my_2d_array2.sum(axis=0)) # Выводим сумму каждого столбеца

[20 10  9 21]


In [ ]:
# np.ones_like создает массив из единиц такой же размерности как и массив а
new_2d_array = np.ones_like(my_2d_array2) # Создаем массив той же размерности, что и my_2d_array2 и заполняем его единицами
print(new_2d_array) # Выводим на экран массив new_2d_кarray

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
new_2d_array2 = np.zeros((5,3)) # Создаем массив из нулей заданной размерности (5,3)
print (new_2d_array2) # Выводи на экран массив new_2d_array2

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
new_2d_array2 = new_2d_array * 2 # Умножим каждый элемент массива на 2
print(new_2d_array2) # Выводим на экран массив new_2d_array2

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
print(new_2d_array)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# поэлементное умножение двух массивов
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[4,3,2],
                 [6,4,3]])
print(arr1 * arr2) # Выведем на экран результат поэлементого умножения массивов

[[ 4  6  6]
 [24 20 18]]


#### Структура np.matrix

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=1087

Подробнее: https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html

In [ ]:
my_matrix = np.matrix(arr1) # Создадим матрицу из массива arr1
print(my_matrix) # Выведем на экран матрицу my_matrix
print(type(arr1)) # Выведем на экран тип переменной arr1
print(type(my_matrix)) # Выведем на экран тип переменной my_matrix

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [ ]:
print(my_matrix.T) # Выведем на экран транспонированную матрицу

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# в случае с np.matrix выполняется матричное умножение, а не поэлементное (!!!)
print(my_matrix * my_matrix.T)


[[14 32]
 [32 77]]


#### Тензоры a.k.a. многомерные массивы

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=1471


In [ ]:
# создаем четыркхмерный массив из случайных значений размерности 2 на 3 на 4 на 5
my_tensor = np.random.random((2, 3, 4, 5))
print(my_tensor)

[[[[0.6031097  0.43092699 0.49457809 0.96770088 0.96881228]
   [0.88334282 0.41943086 0.74994302 0.99992443 0.89027972]
   [0.90926832 0.63720241 0.27521601 0.02527586 0.13176135]
   [0.401371   0.73118929 0.99043974 0.84558549 0.69519924]]

  [[0.7462484  0.41661635 0.20061416 0.6585187  0.40823389]
   [0.65565998 0.88365918 0.18409938 0.02362182 0.46696212]
   [0.85816538 0.27540374 0.4329541  0.05516921 0.6796949 ]
   [0.50081884 0.21926231 0.85063953 0.52004753 0.02312587]]

  [[0.12175731 0.30942525 0.45025321 0.70389175 0.71120046]
   [0.52355839 0.19442352 0.69983017 0.2830477  0.47753994]
   [0.10791838 0.40228388 0.42829902 0.7717735  0.94921038]
   [0.33951051 0.26880622 0.74061038 0.93553858 0.97008438]]]


 [[[0.8173511  0.58582754 0.77915891 0.81752335 0.76420317]
   [0.208228   0.98736894 0.94451237 0.91365519 0.09197298]
   [0.68225178 0.85838584 0.83615206 0.21216032 0.68151576]
   [0.11847151 0.87581894 0.17912256 0.37466628 0.80453631]]

  [[0.14869881 0.51817266 0.14

In [ ]:
# проверяем размерность
print(my_tensor.shape) # Выводим на экран размерность массива my_tensor

(2, 3, 4, 5)


Как поэлементно обращаться к тензорам?

In [ ]:
# элемент с индексами 0 по всем осям
my_tensor[0, 0, 0, 0]

0.603109697348081

In [ ]:
# только первые строки
my_tensor[:,  :, :, 0]

array([[[0.6031097 , 0.88334282, 0.90926832, 0.401371  ],
        [0.7462484 , 0.65565998, 0.85816538, 0.50081884],
        [0.12175731, 0.52355839, 0.10791838, 0.33951051]],

       [[0.8173511 , 0.208228  , 0.68225178, 0.11847151],
        [0.14869881, 0.6406586 , 0.69758509, 0.26063166],
        [0.17357814, 0.57769691, 0.51500676, 0.92502309]]])

In [ ]:
# сумма элементов по второй оси
my_tensor.sum(axis=3)

array([[[3.46512793, 3.94292085, 1.97872395, 3.66378476],
        [2.4302315 , 2.21400247, 2.30138733, 2.11389408],
        [2.29652798, 2.17839971, 2.65948516, 3.25455007]],

       [[3.76406407, 3.14573747, 3.27046576, 2.35261561],
        [1.84746046, 2.42522376, 2.42803423, 2.47640789],
        [2.54394172, 1.8713153 , 2.29002466, 2.8200542 ]]])

### 5. Матричные операции

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=1685

Умножение двух матриц

метод .dot

In [ ]:
print(arr1)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2)

[[4 3 2]
 [6 4 3]]


In [ ]:
# это не умножение(!!!)
## это поэлементное умножение
arr1 * arr2

array([[ 4,  6,  6],
       [24, 20, 18]])

In [ ]:
# вот это умножение:
## метод .dot
arrT = arr1.T
arr3 = arrT.dot(arr2)
print(arr3)

[[28 19 14]
 [38 26 19]
 [48 33 24]]


### 6. Семплирование из распределений

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=1862



Описание всех возможностей модуля np.random:

https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html


In [ ]:
# создаем массив размера 5 на 5 со случайными числами из стандартного нормального распределения
rr = np.random.normal(0, 1, (5,5))
print(rr)

[[-1.64876244  2.42815208 -0.28614529 -1.35202448 -0.14275906]
 [-1.47437539  0.01475247  0.21786697  1.5704047   1.33769413]
 [-0.72312308 -1.47467266  0.33075339  1.26642598 -1.11924887]
 [ 0.23786207  0.66396048 -0.64602133 -0.63776405 -1.7738886 ]
 [ 0.40537837 -0.3534063  -0.19555161 -0.31322363 -1.15463436]]


In [ ]:
rr = np.random.randint(0, 10, (5,5))
print(rr)

[[1 8 4 1 4]
 [0 2 2 5 2]
 [3 0 6 9 5]
 [8 1 9 5 1]
 [4 2 8 8 6]]


In [ ]:
rr = np.random.uniform(-4.33, 2.35, (4,4))
print(rr)

[[-4.0500854   0.52905296 -0.93547943 -3.03734992]
 [ 0.33852648  1.09680788 -3.79664432  2.24413652]
 [-0.46155426  2.13241267 -2.82553722 -0.36551168]
 [ 2.04551211  1.80164279  0.19038021 -4.1574314 ]]


### 7. Чтение файлов

*Разбор данного раздела:* https://youtu.be/T8n-dZUL3wI?t=2151

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# грузим массив из файла .csv
my_data = np.loadtxt('/content/drive/My Drive/Базы/iris.csv', delimiter=',', skiprows=1) # skiprows=1 - пропускаем первую строку, поскольку в ней названия колонок базы 

In [ ]:
# вот то, что мы подгрузили
print(my_data)

[[0.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [1.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [3.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [4.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [5.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [6.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [7.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [8.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [9.00e+00 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.00e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.10e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.30e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.40e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.50e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.60e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.70e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.80e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [1.90e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.00e+01 5.40e+00 3.40e+00 1.70e+00 2.

In [ ]:
# массив имеет тип np.array сразу
type(my_data)

numpy.ndarray

In [ ]:
# тип подгруженных данных - float64
my_data.dtype

dtype('float64')

In [ ]:
my_data.shape

(150, 5)

# **Глоссарий**
array[n1:n2] - срез массива с элемента n1 по n2 (не включительно)

-----------------------

**Основные методы для ndarray **

.dtype - узнать тип данных массива

.shape - узнать размер массива

.reshape((*новый размер*))  - поменять размер массива

.sum() сумма всех элементов

.mean() среднее всех элементов

.min() минимальное значение массива

.max() максимальное значение

.prod() произведение всех элементов

-------------------

np.arange(n) - генерация массива со значениями от 0 до n (не включительно)

np.loadtxt(адрес расположения файла+параметры загрузки)


